services:
  django-api:
    build: .
    container_name: holter-django
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./accounts:/app/accounts
      - django_db:/app/data
    env_file:
      - .env
    environment:
      - DEBUG=False

volumes:
  django_db:
